Feature/refuel service
GiethoornInternationalHarbor/RefuelService pull request #1
Opened 2018-05-19 13:01 UTC by DaanTacoSchool

Up and running

2018-05-19 13:57 UTC, markieo1 requested changes

2018-05-19 13:57 UTC, markieo1 commented on .gitignore
> +.vs
Gitignore incorrect see [VisualStudio.gitignore](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore)

2018-05-19 13:57 UTC, markieo1 commented on README.md
> -# RefuelService
No need for this change

2018-05-19 13:57 UTC, markieo1 commented on RefuelService.App/.gitignore
> +.vs
File should not be needed

2018-05-19 13:57 UTC, markieo1 commented on RefuelService.App/Messaging/RefuelEventHandler.cs
> +            if (refueledShip.ShipService.Name == "Refuel")
We can use the guid for this. Every service will have it's own GUID. That way you can create an constant with a guid for your service and compare this to check if this service is requested. See the ContainerService for an example.

2018-05-19 13:57 UTC, markieo1 commented on RefuelService.App/Properties/launchSettings.json
> +{
Should not be in the repo. Fix by gitignore

2018-05-19 13:57 UTC, markieo1 commented on RefuelService.Core/.gitignore
> +.vs
File not needed.

2018-05-19 13:57 UTC, markieo1 commented on RefuelService.Core/Models/Ship.cs
> +        public ShipService ShipService { get; set; }
Ship should not need to contain a ShipService.

2018-05-19 13:57 UTC, markieo1 commented on RefuelService.Infrastructure/.gitignore
> +.vs
File not needed.

2018-05-19 13:57 UTC, markieo1 commented on RefuelService.Infrastructure/Services/RefuelService.cs
> +                shipService.Price = 2500;
This service should only do the Refueling. Not decided prices / ids / names and such. See ContainerService for example.

2018-05-22 13:49 UTC, Aplicticus requested changes

2018-05-22 13:49 UTC, Aplicticus commented on RabbitMQTestEvents.txt
> +serviceRequested
Remove this file from Git.

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.App/Messaging/RefuelEventHandler.cs
> +
Remove whitespace

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.App/Messaging/RefuelEventHandler.cs
> +
Remove whitespaces

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.App/Messaging/RefuelEventHandler.cs
> +            Task.Run(() => _refuelService.SendShipUndockedAsync(existingShip));
Why do you send event "UndockShip" in ShipUndocked? Refueling Service is not responsible for undocking ships.

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.App/Messaging/RefuelEventHandler.cs
> +            Ship receivedShip = JsonSerializer.Deserialize<Ship>(message);
Use C# default conventions: 
For example: var receivedShip = JsonSerialier.Deserializer<Ship>(message);

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.App/Messaging/RefuelEventHandler.cs
> +            Ship createdShip = await _refuelService.CreateShipAsync(receivedShip);
Use C# default conventions:
For example: var receivedShip = JsonSerialier.Deserializer(message);

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.App/Messaging/RefuelEventHandler.cs
> +            Ship receivedShip = JsonSerializer.Deserialize<Ship>(message);
Use C# default conventions:
For example: var receivedShip = JsonSerialier.Deserializer(message);

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.App/Messaging/RefuelEventHandler.cs
> +            Ship existingShip = await _refuelService.GetShipAsync(receivedShip.Id);
Use C# default conventions:
For example: var receivedShip = JsonSerialier.Deserializer(message);

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.App/Messaging/RefuelEventHandler.cs
> +            Task.Run(() => _refuelService.SendShipDockedAsync(createdShip));
Why do you send event "DockShip" in ShipDocked? Refueling Service is not responsible for docking ships.

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.App/Messaging/RefuelEventHandler.cs
> +
Remove whitespaces

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.App/Messaging/RefuelEventHandler.cs
> +                Ship existingShip = await _refuelService.GetShipAsync(receivedShipService.ShipId);
Use C# default conventions:
For example: var receivedShip = JsonSerialier.Deserializer(message);

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.Core/Messaging/IEventPublisher.cs
> +        Task HandleEventAsync<T>(EventTypes eventType, T message);
Wrong function name. EventPublisher handles incoming events?

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.Core/Models/ServiceRequest.cs
> +
Remove whitespaces

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.Core/Models/Ship.cs
> +        public string Email { get; set; }
Remove email property

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.Core/Models/Ship.cs
> +        public List<ShipService> ShipServices { get; set; }
Remove this list of ShipServices

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.Core/Models/ShipServiceConstants.cs
> +
Remove whitespaces

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.Core/Repositories/IShipRepository.cs
> +		/// Gets the ship.
Fix identation

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.Core/Services/IRefuelService.cs
> +        Task<Ship> SendShipDockedAsync(Ship ship);
Remove this function, RefuelService is not responsible for this action.

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.Core/Services/IRefuelService.cs
> +        Task<Ship> SendShipUndockedAsync(Ship ship);
Remove this function, RefuelService is not responsible for this action.

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.Infrastructure/Repositories/ShipRepository.cs
> +
Remove white spaces / lines

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.Infrastructure/Services/RefuelService.cs
> +
Remove white lines

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.Infrastructure/Services/RefuelService.cs
> +
Remove white space / lines

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.Infrastructure/Services/RefuelService.cs
> +            return Task.Run(async () =>
Remove Task.Run(async () => ). Just return the await. Set async before Task. Example: public async Task<x> name ().

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.Infrastructure/Services/RefuelService.cs
> +            return Task.Run(async () =>
Remove Task.Run(async () => ). Just return the await. Set async before Task. Example: public async Task<x> name ().

2018-05-22 13:49 UTC, Aplicticus commented on RefuelService.Infrastructure/Services/RefuelService.cs
> +            return Task.Run(async () =>
Remove Task.Run(async () => ). Just return the await. Set async before Task. Example: public async Task<x> name ().

2018-05-22 14:16 UTC, Aplicticus approved these changes

2018-05-22 14:19 UTC, markieo1 requested changes

2018-05-22 14:19 UTC, markieo1 commented on RefuelService.Infrastructure/Database/RefuelDbContext.cs
> +namespace Refuel.Infrastructure.Database
Namespace mismatch, should be RefuelService.Infrastructure.Database

2018-05-22 14:22 UTC, Daan298261 commented on RefuelService.Infrastructure/Database/RefuelDbContext.cs
> +namespace Refuel.Infrastructure.Database
fixed

2018-05-22 14:22 UTC, markieo1 approved these changes

2018-05-22 14:30 UTC, merged